apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-srv-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: likithjogi/app-srv:v2
        ports:
        - containerPort: 5000
